version: '3.8'

services:
  stellar-quickstart:
    image: stellar/quickstart:latest
    container_name: stellar-quickstart
    ports:
      - '8000:8000'
    volumes:
      - stellar-data:/opt/stellar
    command: --local

volumes:
  stellar-data:
